version: 2
jobs:
   node8:
     docker:
       - image: circleci/node:8
     steps:
       - checkout
       - restore_cache:
           keys:
             - npm-deps-{{ checksum "package.json" }}
       - run: npm install
       - save_cache:
           key: npm-deps-{{ checksum "package.json" }}
           paths:
             - node_modules/
       - run: npm test

   node10:
     docker:
       - image: circleci/node:10
     steps:
       - checkout
       - restore_cache:
           keys:
             - npm-deps-{{ checksum "package.json" }}
       - run: npm install
       - save_cache:
           key: npm-deps-{{ checksum "package.json" }}
           paths:
             - node_modules/
       - run: npm test
       
   node12:
     docker:
       - image: circleci/node:12.9
     steps:
       - checkout
       - restore_cache:
           keys:
             - npm-deps-{{ checksum "package.json" }}
       - run: npm install
       - save_cache:
           key: npm-deps-{{ checksum "package.json" }}
           paths:
             - node_modules/
       - run: npm test
       - run: npm run coverage
       
workflows:
  version: 2
  node8_node10_node12:
    jobs:
      - node8
      - node10
      - node12
